/*
Author: Tomas Rohr, rohr.tomas@gmail.com
Last change date: 2017-09-01
*/
SET TERMOUT OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET AUTOCOMMIT OFF
SET EXITCOMMIT OFF
SET PAGESIZE 50000
SET LINESIZE 500
SET LONG 50000
SET TRIMSPOOL ON
SET TIMING OFF
SET VERIFY OFF
SET TAB OFF
SET ECHO OFF

/* Define editor as you wish */
def _editor = "C:\Program Files (x86)\Notepad++\notepad++.exe"


/* get details about this session */
VAR sid NUMBER
VAR serial# NUMBER
VAR audsid NUMBER
VAR tracefile VARCHAR2(200)
/* this variable is important for function of other scripts */
VAR owner VARCHAR2(128)



 
BEGIN	
	:sid := SYS_CONTEXT('USERENV','SID');
	:audsid := SYS_CONTEXT('USERENV','SESSIONID');
	SELECT USER
      INTO :owner
      FROM DUAL;
END;
/

BEGIN
    SELECT SERIAL#
      INTO :serial#
      FROM V$SESSION
      WHERE AUDSID = SYS_CONTEXT('USERENV','SESSIONID');

    SELECT 
		PAR.VALUE ||
        CASE WHEN PAR.VALUE LIKE '%/%' THEN '/' ELSE '\' END ||
        LOWER(TH.INSTANCE) ||
         '_ora_' || LTRIM(TO_CHAR(P.SPID,'FM99999')) || '.trc' AS FILENAME
      INTO   :tracefile
      FROM V$PROCESS P,
           V$SESSION S,
           V$PARAMETER PAR,
           V$THREAD TH
      WHERE  S.AUDSID = SYS_CONTEXT('USERENV','SESSIONID')
	    AND P.ADDR = S.PADDR
        AND PAR.NAME = 'user_dump_dest';
END;
/

/* set sqlplus prompt */
DEFINE GNAME=IDLE
COLUMN GLOBAL_NAME NEW_VALUE GNAME
SELECT LOWER(USER) || '@' ||
       SUBSTR(GLOBAL_NAME,1,DECODE(DOT,0,LENGTH(GLOBAL_NAME),DOT-1))|| ' ' ||:owner GLOBAL_NAME
FROM (SELECT GLOBAL_NAME,INSTR(GLOBAL_NAME,'.') DOT FROM GLOBAL_NAME);
SET SQLPROMPT '&GNAME> '

SET TERMOUT ON
SET FEEDBACK OFF
COLUMN SID FORMAT 99999999
COLUMN AUDSID FORMAT 99999999
COLUMN SERIAL# FORMAT 99999999

SELECT 
  :sid AS SID,
  :serial# AS SERIAL#,
  :audsid AS AUDSID
FROM DUAL;

EXEC IF :tracefile IS NULL THEN DBMS_OUTPUT.PUT_LINE('We don''t have select previlege on V$ tables.'); END IF
EXEC IF :tracefile IS NOT NULL THEN DBMS_OUTPUT.PUT_LINE('Session trace file: ' || :tracefile); END IF

/* other sesssion settings */

ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS';
ALTER SESSION SET NLS_TIMESTAMP_FORMAT = 'YYYY-MM-DD HH24:MI:SS.FF';
ALTER SESSION SET NLS_TIMESTAMP_TZ_FORMAT = 'YYYY-MM-DD HH24:MI:SS.FF TZR';

SET FEEDBACK ON

COLUMN NAME FORMAT A30
COLUMN PARAMETER FORMAT A50
COLUMN VALUE FORMAT A60
COLUMN OWNER FORMAT A30
COLUMN TABLE_NAME FORMAT A30
COLUMN TABLE_OWNER FORMAT A30
COLUMN STATUS FORMAT A10
COLUMN USER FORMAT A30
COLUMN USERNAME FORMAT A30
COLUMN GRANTEE FORMAT A30
COLUMN ROLE_NAME FORMAT A30
COLUMN GRANTED_ROLE FORMAT A30
COLUMN ROLE FORMAT A30
COLUMN COLUMN_NAME FORMAT A30
COLUMN PRIVILEGE FORMAT A30
COLUMN OBJECT_NAME FORMAT A30
COLUMN PARTITION_NAME FORMAT A30
COLUMN SUBOBJECT_NAME FORMAT A30
COLUMN OBJECT_TYPE FORMAT A23
COLUMN NUM_ROWS FORMAT 999G999G999


