/*
Author: Tomas Rohr, rohr.tomas@gmail.com
Last change date: 2017-07-15
*/

COLUMN "ROLE/USERNAME" FORMAT A30
COLUMN PRIVILEGE FORMAT A34

SELECT
     ROLE AS "ROLE/USERNAME"
    ,PRIVILEGE
    ,ADMIN_OPTION
FROM ROLE_SYS_PRIVS
WHERE ROLE IN (
    SELECT ROLE
    FROM USER_ROLE_PRIVS
)
UNION ALL
SELECT
     USERNAME
    ,PRIVILEGE
    ,ADMIN_OPTION
FROM USER_SYS_PRIVS
ORDER BY 1,2
;
