/*
Author: Tomas Rohr, rohr.tomas@gmail.com
Last change date: 2017-11-02
*/
SET VERIFY OFF

/*
Do not prompt for substitution variables values.
Use '%' as default value for substitution variable.
*/
COLUMN 1 NEW_VALUE 1
COLUMN 2 NEW_VALUE 2
SET FEEDBACK OFF
SELECT NULL "1", NULL "2" FROM DUAL WHERE 1=0;
SET FEEDBACK ON

COLUMN PK FORMAT 99
COLUMN PTK FORMAT 99
COLUMN ID FORMAT 999
COLUMN COLUMN_NAME FORMAT A30
COLUMN DATATYPE FORMAT A20
COLUMN NULLABLE FORMAT A1 HEADING "N"
COLUMN VIRTUAL FORMAT A1 HEADING "V"
COLUMN HIDDEN FORMAT A1 HEADING "H"
COLUMN DEFAULT_VALUE FORMAT A45


SELECT 
   A.ACC_POSITION AS PK,
   A.APC_POSITION AS PTK,
   A.COLUMN_ID AS ID,
   A.COLUMN_NAME AS COLUMN_NAME,
   A.DATA_TYPE ||
   CASE WHEN A.DATA_TYPE LIKE '%CHAR%' 
     THEN '(' || A.DATA_LENGTH ||
       CASE WHEN A.CHAR_USED = 'C' THEN ' CHAR)' ELSE ' BYTE)' END
   WHEN A.DATA_TYPE IN 'NUMBER'
     THEN CASE WHEN A.DATA_PRECISION IS NOT NULL AND A.DATA_SCALE IS NOT NULL
               THEN '('|| A.DATA_PRECISION ||','|| A.DATA_SCALE ||')'
          END
   END AS DATATYPE,  
   A.NULLABLE AS NULLABLE,
   SUBSTR(A.VIRTUAL_COLUMN,1,1) AS VIRTUAL,
   SUBSTR(A.HIDDEN_COLUMN,1,1) AS HIDDEN,
   A.DATA_DEFAULT AS DEFAULT_VALUE
from (   
   SELECT
      ACC.POSITION AS ACC_POSITION,
      APC.COLUMN_POSITION AS APC_POSITION,
      AI.COLUMN_ID,
      AI.OWNER,
      AI.TABLE_NAME,
      AI.COLUMN_NAME,
      AI.DATA_TYPE,
      AI.DATA_LENGTH,
      AI.CHAR_USED,
      AI.DATA_PRECISION,
      AI.DATA_SCALE,
      AI.NULLABLE,
      AI.VIRTUAL_COLUMN,
      AI.HIDDEN_COLUMN,
      AI.DATA_DEFAULT
   FROM
      ALL_TAB_COLS AI
      LEFT OUTER JOIN ALL_CONSTRAINTS AC
        ON AC.OWNER = AI.OWNER
       AND AC.TABLE_NAME = AI.TABLE_NAME
       AND AC.CONSTRAINT_TYPE = 'P'
      LEFT OUTER JOIN ALL_CONS_COLUMNS ACC
        ON ACC.OWNER = AC.OWNER
       AND ACC.TABLE_NAME = AC.TABLE_NAME
       AND ACC.COLUMN_NAME = AI.COLUMN_NAME
       AND ACC.CONSTRAINT_NAME = AC.CONSTRAINT_NAME
      LEFT OUTER JOIN ALL_PART_KEY_COLUMNS APC
         ON APC.OWNER = AI.OWNER
        AND APC.NAME = AI.TABLE_NAME
        AND APC.COLUMN_NAME = AI.COLUMN_NAME
        AND APC.OBJECT_TYPE = 'TABLE'
   WHERE 1=1
   -- if both &1 and &2 are not null then (owner like '&1' and table_name like '&2')
   AND (('&1' IS NULL OR '&2' IS NULL) OR (AI.OWNER LIKE '&1' AND AI.TABLE_NAME LIKE '&2'))
   -- if &1 is not null and &2 is null then (owner=:owner and table_name like '&1')
   AND	(('&1' IS NULL OR '&2' IS NOT NULL) OR (AI.OWNER=:OWNER AND AI.TABLE_NAME LIKE '&1'))
) A
order by A.COLUMN_ID;

UNDEF 1
UNDEF 2


